//go:build devel || debug || race

package main

import (
	"net/http"
	"strings"

	"github.com/linkdata/rinse/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/linkdata/rinse/rinser"
	httpSwagger "github.com/swaggo/http-swagger"
)

const RinseDevel = true

func maybeSwagger(listenUrl string) {
	docs.SwaggerInfo.Version = strings.TrimPrefix(rinser.PkgVersion, "v")
	docs.SwaggerInfo.Host = listenUrl
	http.DefaultServeMux.Handle("GET /api/", httpSwagger.Handler(
		httpSwagger.URL(listenUrl+"/docs/swagger.json"),
	))
}
