//go:build devel || debug || race

package main

import (
	"net/http"
	"strings"

	"github.com/linkdata/rinse/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/linkdata/rinse/rinser"
	httpSwagger "github.com/swaggo/http-swagger"
)

const RinseDevel = true

func maybeSwagger(next http.Handler, listenUrl string) (h http.Handler) {
	docs.SwaggerInfo.Version = strings.TrimPrefix(rinser.PkgVersion, "v")
	docs.SwaggerInfo.Host = listenUrl
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet && strings.HasPrefix(r.URL.Path, "/api/") {
			httpSwagger.Handler(
				httpSwagger.URL(listenUrl+"/docs/swagger.json"),
			).ServeHTTP(w, r)
			return
		}
		next.ServeHTTP(w, r)
	})
}
