FROM alpine:latest AS rinse-pdftoppm
LABEL org.opencontainers.image.source="https://github.com/linkdata/rinse"

RUN apk --no-cache -U upgrade && \
    apk --no-cache add poppler-utils

RUN addgroup -g 1000 rinse && adduser -u 1000 -s /bin/true -G rinse -h /var/rinse -D rinse
RUN mkdir -p /var/rinse && chmod 777 /var/rinse
WORKDIR /
USER rinse
