name: Code checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
    
      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test -tags debug ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
