name: Dependabot merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - closed

permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.action != 'closed' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'linkdata/rinse'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  increment-patch:
    if: >
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.base.ref == 'main' &&
      github.repository == 'linkdata/rinse'
    uses: ./.github/workflows/increment-patch.yml
    with:
      checkout_ref: main
    secrets: inherit
