name: Increment main branch patch level then run build-image

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  increment-patch-level:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.TAG_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install gitsemver
        run: go install github.com/linkdata/gitsemver@v1.5.0

      - name: Dump environment and check current version
        run: |
          env
          git status
          git branch --show-current
          gitsemver -debug

      - name: Increment patch level
        id: version
        run: |
          echo -n "TAG_NAME=" >> $GITHUB_OUTPUT
          gitsemver -incpatch | tee -a $GITHUB_OUTPUT

  build-image:
    needs: increment-patch-level
    uses: ./.github/workflows/build-image.yml
    with:
      new_version: ${{ needs.increment-patch-level.outputs.new_version }}
    secrets: inherit
