name: Increment patch level then run build-image

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  increment-patch-level:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.TAG_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install gitsemver
        run: go install github.com/linkdata/gitsemver@v1.9.0

      - name: Debug environment
        run: |
          env
          gitsemver -gopackage

      - name: Increment patch level
        id: version
        run: |
          echo -n "TAG_NAME=" >> $GITHUB_OUTPUT
          gitsemver -incpatch | tee -a $GITHUB_OUTPUT

  build-image:
    needs: increment-patch-level
    uses: ./.github/workflows/build-image.yml
    with:
      new_version: ${{ needs.increment-patch-level.outputs.new_version }}
    secrets: inherit
