name: Increment patch level then run build-image

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  increment-patch-level:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.TAG_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install gitsemver
        run: go install github.com/linkdata/gitsemver@v1.2.0

      - name: Retrieve version and increment patch level
        id: version
        run: |
          echo "TAG_NAME=$(gitsemver -incpatch)" >> $GITHUB_OUTPUT

  build-image:
    needs: increment-patch-level
    uses: ./.github/workflows/build-image.yml
    with:
      new_version: ${{ needs.increment-patch-level.outputs.new_version }}
    secrets: inherit
